import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, Show, SignInButton } from "@clerk/nextjs";
import SoftPillButton from "@/components/ui/soft-pill-button";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Giti Flex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <header className="fixed left-4 top-4 z-50 flex items-center gap-2">
            <Show when="signed-out">
              <SignInButton mode="modal">
                <SoftPillButton variant="secondary">
                  Sign in with GitHub
                </SoftPillButton>
              </SignInButton>
            </Show>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
